### PR TITLE
fixes 2nd step of 'Easy Installation'

### PR DESCRIPTION
**Pull request by rabellamy**

### CODE REVIEW

**Comment by cweagans** [comment]
This should work without the quotes. Are you seeing something different?

**Comment by rabellamy** [comment]
I only got the command to work locally by adding the quotes. Could I be missing something?

**Comment by cweagans** [comment]
Huh, weird. I just tried it out and it was broken for me too. I probably just installed pubstack-shell manually. Does `composer global require nbcutechnology/pubstack-shell:~1.0` work for you?

**Comment by rabellamy** [comment]
`composer global require nbcutechnology/pubstack-shell:~1.0` works!

**Comment by rabellamy** [comment]
Should I update this PR?

**Comment by cweagans** [comment]
Sounds good to me.

**Comment by scottrigby** [comment]
Great guys :+1:

**Pull request merged**
